import { Address } from '@ton/core';

export const MASTER_ADDRESS = Address.parse('EQC8rUZqR_pWV1BylWUlPNBzyiTYVoBEmQkMIQDZXICfnuRr');

export const OPCODES = {
    JETTON_TRANSFER_NOTIFICATION: 0x7362d09c,

    SUPPLY: 0x1,
    WITHDRAW: 0x2,
    LIQUIDATE: 0x3,

    SUPPLY_USER: 0x11,
    WITHDRAW_USER: 0x21,
    LIQUIDATE_USER: 0x31,

    SUPPLY_SUCCESS: 0x11a,
    WITHDRAW_COLLATERIZED: 0x211,
    LIQUIDATE_SATISFIED: 0x311,

    WITHDRAW_SUCCESS: 0x211a,
    WITHDRAW_FAIL: 0x211f,
    LIQUIDATE_SUCCESS: 0x311a,
    LIQUIDATE_FAIL: 0x311f,
};
